### PR TITLE
Show version in the output

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by Nyholm** [comment]
I suspect there is something wrong here.. 

This action: https://github.com/async-aws/aws/pull/478/checks?check_run_id=578865669#step:4:1 claim that there is things needed to be changed. 

However, when running locally, I have no changes.. 

```
➜   ✗ php-cs-fixer --version                        
PHP CS Fixer 2.16.1 Yellow Bird by Fabien Potencier and Dariusz Ruminski
➜   ✗ php-cs-fixer fix --dry-run --diff-format udiff
Loaded config default from "/Users/tobias/Workspace/PHPStorm/aws/.php_cs".
Using cache file ".php_cs.cache".

Checked all files in 0.336 seconds, 16.000 MB memory used

```

I suspect that version `2.16.1.2` is running PHP-cs-fixer `2.16.2`

**Comment by OskarStark** [comment]
Can you verify this by checking out the corresponding dockerhub Tag locally?

**Comment by OskarStark** [comment]
Checking your action, you are running 2.16.0 and locally 2.16.1, no?

**Comment by Nyholm** [comment]
Yeah, 2.16.0 was working. Since PHP-CS-fixer 2.16.2 had a bug, I just lowered the version of this action until it was working.

**Comment by Nyholm** [comment]
Could we merge this and release a new version with 2.16.3?

**Comment by OskarStark** [comment]
Sure, will do

**Pull request merged**
