### PR TITLE
Use always newest version of php-cs-fixer

### PR DESCRIPTION
**Pull request by alexander-schranz**
I would use the newest version or make it configureable which version it should use and make it possible to use always the latest version.

### CODE REVIEW

**Comment by OskarStark** [comment]
currently it is „configurable“ via the docker tag which is based on the release on github.

**Comment by alexander-schranz** [comment]
@OskarStark Ah okay so this releases are greated automatically?

**Comment by OskarStark** [comment]
Unfortunately not, I do this whenever a new release is created 👎🏻
Automating this would be very nice, but I don’t know how

**Comment by Nyholm** [comment]
Lets merge this to a separate branch. `v2`

That will "solve" https://github.com/OskarStark/php-cs-fixer-ga/issues/17. 
A user can then do the followng to always get the latest php-cs-fixer. 

```yaml
- name: PHP-CS-Fixer
        uses: OskarStark/php-cs-fixer-ga@v2
        with:
          args: --dry-run --diff-format udiff
```

------

There will be more maintenance cost to merge features into 2 branches. But Im not sure how many features that is usually added to this lib.

**Comment by OskarStark** [comment]
TBH I don't understand the problem here. using `@master` will always use the latest version of PHP-CS-Fixer

For a specific version you can use it, it gets tagged automatically on dockerhub.

**Comment by glensc** [comment]
I agree with @OskarStark this PR is not needed, just that maintainer needs to keep on to push over `@master` each time the new version is updated.

however, I like the `@v2` tag proposed by @Nyholm, to be somewhat semver compatible, in case php-cs-fixer v3 appears.

**Comment by fabiofdsantos** [comment]
> Unfortunately not, I do this whenever a new release is created 👎🏻
> Automating this would be very nice, but I don’t know how

We can do it via a GitHub action but it requires some implementation effort ofc..

**Comment by rdwebdesign** [comment]
I think this action could help here.

**Comment by rdwebdesign** [comment]
I think this action could hep here: https://github.com/marketplace/actions/find-latest-tag.

**Comment by OskarStark** [comment]
Check
* #102 
and 

* https://github.com/OskarStark/phpstan-ga/pull/58#issuecomment-1702263614

for more infos

**Pull request closed without merging**
