### PR TITLE
Use PHP-CS-Fixer 3.4.0

### PR DESCRIPTION
**Pull request by db306**
Add support for PHP 8.1 and PHP-CS Fixer version 3.4.0

### CODE REVIEW

**Comment by OskarStark** [comment]
Thanks

**Comment by db306** [comment]
Thanks for updating :)
Last thing in order to make version 3.4.0 work is to tag it with 3.4.0, it only has the latest tag.

https://hub.docker.com/layers/oskarstark/php-cs-fixer-ga/latest/images/sha256-8f11136dc16525e0c916014e5bfa29a8ddda0cefc49de65f37b49d860dd77058?context=explore

**Comment by db306** [comment]
Also, the image built with 3.4.0 is using PHP 8.0.13 instead of 8.1.0 which fails running PHP CS on latest PHP versions

**Comment by db306** [comment]
@OskarStark not sure you have notifications on closed issues ^^ Hope you get to read this

**Comment by OskarStark** [comment]
Oh indeed, open for a new PR changing the PHP version in master branch? Thanks

**Comment by db306** [comment]
@OskarStark Done
https://github.com/OskarStark/php-cs-fixer-ga/pull/46

**Pull request closed without merging**
